apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cassandra.yaml
  - gateway.yaml
  - grafana.yaml
  - message.yaml
  - moderation.yaml
  - nats.yaml
  - notification.yaml
  - postgres.yaml
  - presence.yaml
  - redis.yaml
  - user.yaml
